name: ELK Stack # ELK Stack
description: |
  The ELK App contains ElasticSearch Kibana Logstach # Description of the Catalog Entry
version: 5.5.2-elk # Version of the Catalog to be used
category: elk # Category to be used for searching catalog entries
maintainer: luozf <luozhaofeng@finogeeks.club> # The maintainer of the catalog entry
license: Apache2 # The license
projectURL: # A URL related to the catalog entry
